[build]
    base = "" # Leave it empty if the project root is correct
    publish = "out" # or ".next" for Next.js
    command = "npm run build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200