import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./shared/components/header";
import Footer from "./shared/components/footer";
import { ThemeProvider } from "./shared/providers/ThemeProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Create Next App",
  description: "Generated by create next app",
  title: {
    // absolute: "Next App - Absolute", // Absolute title for the entire site
    default: "Next App", // Default title
    template: "%s | Next App", // %s will be replaced by the page title when provided
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <base href="/" />
      </head>
      <ThemeProvider>
        <body
          suppressHydrationWarning
          className={
            inter.className +
            " " +
            "bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-gray-100 transition-all duration-500 ease-in-out"
          }
        >
          <Header />
          <div className="container pt-20 mb-15">{children}</div>
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
